services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile.prod
    restart: always
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis

  worker:
    build:
      context: .
      dockerfile: apps/worker/Dockerfile.prod
    restart: always
    environment:
      REDIS_HOST: redis
      NODE_ENV: production
    depends_on:
      - db
      - redis

volumes:
  postgres_data:
